## 03 ``numpy.array`` 基本操作

In [1]:
import numpy as np
np.random.seed(0)

x = np.arange(10)

In [2]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
X = np.arange(15).reshape((3, 5))

In [4]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### ``numpy.array`` 的基本属性

In [5]:
x.ndim

1

In [6]:
X.ndim

2

In [7]:
x.shape

(10,)

In [8]:
X.shape

(3, 5)

In [9]:
x.size

10

In [10]:
X.size

15

### ``numpy.array`` 的数据访问

方法为：arr1[ start:end ：step]

- start 表示开始位置，默认为 0；
- end 表示结束位置，默认为最后一个元素的位置 +1；
- step 表示步长，即两个元素直接相隔的距离，默认为 1。

In [11]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
x[0]

np.int64(0)

In [13]:
x[-1]

np.int64(9)

In [14]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
X[0][0] # 不建议！

np.int64(0)

#### 二维数组访问
- 方法为：arr2[row，col]，row 表示第几行，col 表示第几列。

In [16]:
X[0, 0]

np.int64(0)

In [17]:
X[0, -1]

np.int64(4)

In [18]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
x[0:5]

array([0, 1, 2, 3, 4])

In [20]:
x[:5]

array([0, 1, 2, 3, 4])

In [21]:
x[5:]

array([5, 6, 7, 8, 9])

In [22]:
x[4:7]

array([4, 5, 6])

In [23]:
x[::2]

array([0, 2, 4, 6, 8])

In [24]:
x[1::2]

array([1, 3, 5, 7, 9])

In [25]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [26]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

#### 二维数组访问 

方法为：arr2[[row1,row2,...][col1,col2,...]]

访问的是数组（row1，col1）、（row2、col2）、……位置上的元素，这点初次使用者需要多多注意。


访问连续的元素

方法为：arr2[row_start:row_end：step,col_start:col_end：step]，row_start 表示行的开始位置、row_end 表示行的结束位置、step 表示步长、col_start 表示列的开始位置、col_end 表示列的结束位置。同样开始位置默认为 0，结束位置默认为最后一个元素所在位置 +1，步长默认为 1 且可省略。

In [27]:
X[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [28]:
X[:2][:3] # 结果不一样，在numpy中使用","做多维索引

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [29]:
X[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [30]:
X[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [31]:
X[0, :]

array([0, 1, 2, 3, 4])

In [32]:
X[:, 0]

array([ 0,  5, 10])

### Subarray of ``numpy.array``

In [33]:
subX = X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [34]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [35]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [36]:
X[0, 0] = 0
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [37]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [38]:
subX = X[:2, :3].copy()

In [39]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [40]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### Reshape

In [41]:
x.shape

(10,)

In [42]:
x.ndim

1

In [43]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [44]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
A = x.reshape(2, 5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [46]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
B = x.reshape(1, 10)
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [48]:
B.ndim

2

In [49]:
B.shape

(1, 10)

In [50]:
x.reshape(-1, 10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [51]:
x.reshape(10, -1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [52]:
x.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [53]:
x.reshape(3, -1)

ValueError: cannot reshape array of size 10 into shape (3,newaxis)

### 三维数组的索引与切片

方法为：arr3[dim1，dim2 , dim3]，dim1、dim2、dim3 分别代表三维数组的三个维度的索引。

- 方法为：arr2[[row1,row2,...],[col1,col2,...],[high1,high2]]，访问的是数组（row1，col1,high1）、（row2、col2,high2）...位置上的元素。



In [59]:
space=np.array([
    [[5,4,8],[5,9,2],[4,5,3]],
    [[4,9,6],[2,2,5],[4,3,4]],
    [[4,2,1],[7,6,3],[4,6,5]]])
space[0,0,0]

np.int64(5)

查询空间坐标为（0，0，0）、（0，1，0），（1，2，2）的子空间的蚊子密度为例，示例如下：

In [61]:
Space=np.array([
    [[5,4,8],[5,9,2],[4,5,3]],
    [[4,9,6],[2,2,5],[4,3,4]],
    [[4,2,1],[7,6,3],[4,6,5]]])
Space[[0,0,1]]

array([[[5, 4, 8],
        [5, 9, 2],
        [4, 5, 3]],

       [[5, 4, 8],
        [5, 9, 2],
        [4, 5, 3]],

       [[4, 9, 6],
        [2, 2, 5],
        [4, 3, 4]]])

In [62]:
Space[[0,0,1],[0,1,2],[0,0,2]]

array([5, 5, 4])

### 索引的高级操作

布尔索引就是传入一个与数组形状相同的元素值为布尔类型的列表或数组，然后就能索引到列表中 True 的位置相同的元素。

- 方法为：arr[bool_list]，其中 bool_list 为布尔类型的列表。

In [63]:
row=['美的','格力','海尔','西门子']
data=np.array([[3800,1,15],[4000,8,20],[5000,2,30],[4000,20,50]])
bool_list=[False,False,True,False]
print(data[bool_list])

[[5000    2   30]]


####  条件索引

方法为：arr[条件语句]或 numpy.where(条件语句) 
- 其中第一个方法直接返回符合条件的元素的值，而第二个方法则返回符合条件的元素的位置。

In [64]:
Score2=np.array([69,80,90,40,60,20,90,94,90,99])#学生的成绩
con=Score2>60#筛查出分数大于60的分数
print('条件的布尔列表',con)
print('大于60的学生成绩',Score2[con])#查看大于60分的学生成绩
print('大于60的学生数组下标',np.where(Score2>60))

条件的布尔列表 [ True  True  True False False False  True  True  True  True]
大于60的学生成绩 [69 80 90 90 94 90 99]
大于60的学生数组下标 (array([0, 1, 2, 6, 7, 8, 9]),)
