##  ``Numpy`` 中arg运算

找索引位置

In [1]:
import numpy as np

In [27]:
x = np.random.normal(0, 1, 1000000)

### 索引

argmin 最小位置索引，argmax最大位置索引

In [30]:
np.argmin(x)

np.int64(854623)

In [31]:
x[854623]

np.float64(-4.817738972078378)

In [29]:
np.min(x)

np.float64(-4.817738972078378)

In [32]:
np.argmax(x)

np.int64(331845)

In [33]:
x[331845]

np.float64(4.560598900470751)

In [34]:
np.max(x)

np.float64(4.560598900470751)

### 排序和使用索引

In [9]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [10]:
np.random.shuffle(x)
x

array([14,  5,  0,  2, 12, 13,  6, 10, 11,  3, 15,  4,  8,  9,  1,  7])

In [11]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
x

array([14,  5,  0,  2, 12, 13,  6, 10, 11,  3, 15,  4,  8,  9,  1,  7])

In [13]:
x.sort()

In [14]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [15]:
X = np.random.randint(10, size=(4,4))
X

array([[0, 3, 9, 7],
       [2, 3, 6, 2],
       [4, 3, 8, 4],
       [4, 2, 7, 6]])

In [16]:
np.sort(X, axis=0)

array([[0, 2, 6, 2],
       [2, 3, 7, 4],
       [4, 3, 8, 6],
       [4, 3, 9, 7]])

In [17]:
np.sort(X, axis=1)

array([[0, 3, 7, 9],
       [2, 2, 3, 6],
       [3, 4, 4, 8],
       [2, 4, 6, 7]])

#### 使用索引

In [18]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [19]:
np.random.shuffle(x)

In [20]:
x

array([11,  0, 14, 10,  5,  7, 13,  6,  1,  3, 12, 15,  4,  8,  2,  9])

In [21]:
np.argsort(x)

array([ 1,  8, 14,  9, 12,  4,  7,  5, 13, 15,  3,  0, 10,  6,  2, 11])

partition下面是代表 找出最小的３个元素放在前面 位置顺序不用管。 

In [22]:
np.partition(x, 3)

array([ 0,  1,  2,  3,  6,  7,  4,  8,  5,  9, 12, 15, 13, 10, 14, 11])

In [23]:
np.argpartition(x, 3)

array([ 1,  8, 14,  9,  7,  5, 12, 13,  4, 15, 10, 11,  6,  3,  2,  0])

In [24]:
X

array([[0, 3, 9, 7],
       [2, 3, 6, 2],
       [4, 3, 8, 4],
       [4, 2, 7, 6]])

np.argsort(X, axis=1) 按行从小到大排， 索引位置就是 列索引号，第几列 

In [25]:
np.argsort(X, axis=1)

array([[0, 1, 3, 2],
       [0, 3, 1, 2],
       [1, 0, 3, 2],
       [1, 0, 3, 2]])

In [26]:
np.argpartition(X, 2, axis=1)

array([[0, 1, 3, 2],
       [0, 3, 1, 2],
       [1, 0, 3, 2],
       [1, 0, 3, 2]])