## 通过NearestNeighbors 找出最相似的用户

然后拿这个用户的习惯商品，推荐给另外的用户。 

In [7]:
from sklearn import neighbors
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics.pairwise import cosine_similarity,cosine_distances

# 假设用户给６个相同商品打个分数，０－１００分
user1=np.array([50,30,25,76,89,100])
user2=np.array([79,67,67,90,70,60])
user3=np.array([10,45,20,78,50,50])
user4=np.array([66,78,50,80,30,40])
user5=np.array([35,11,80,40,35,45])
user6=np.array([21,82,30,68,25,55])
user7=np.array([89,67,25,59,80,75])


def ad_cos(arr1,arr2):  #修正的余弦相似性
    arr1=arr1-arr1.mean()
    arr2=arr2-arr2.mean()
    #return 1-cosine_similarity(arr1.reshape(1,arr1.size),arr2.reshape(1,arr2.size))
    return cosine_distances(arr1.reshape(1,arr1.size),arr2.reshape(1,arr2.size))

# 指定算法
neighbors=neighbors.NearestNeighbors(metric=ad_cos)
samples=np.concatenate((user1,user2,user3,user4,user5,user6,user7)).reshape(-1,6)
newUser=np.array([45,60,60,55,20,55]).reshape(-1,6)   #这是一个新用户

# 故意给一样的。
newUser2=np.array([89,67,25,59,80,75]).reshape(-1,6)   #这是一个新用户

neighbors.fit(samples)
# print(samples)

# 找２个最相似的
result=neighbors.kneighbors(newUser,2)
print(result)

# 找1个最相似的
result1=neighbors.kneighbors(newUser2,1)
# 第６个用户
print(result1[1][0][0])


(array([[0.40510145, 0.42247772]]), array([[3, 5]]))
6


[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
