## 04 创建 ``numpy.array``

In [1]:
import numpy as np

### ``numpy.array``

In [2]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 其他创建 ``numpy.array`` 的方法

#### ``zeros`` 填充全０的

默认浮点数类型

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros(10, dtype=float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.zeros(shape=(3, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

#### ones 填充全是１的

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### full， 填充指定值的

In [9]:
np.full((3, 5), 666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [10]:
np.full(fill_value=666, shape=(3, 5))

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

#### eye 方法创建对角数组


In [19]:
eyeArry=np.eye(5)  
eyeArry

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 从现有数组生成新数组

#### array方法

numpy.array(object，dtype，shape)

- object 为要转化为 Numpy 数组的数据对象，可以为列表、元组或者数组；
- dtype 为转化后数组的数据类型，若不设置则与原数据对象的数据类型保持一致；
- shape 用于指定数组的形状，若不设置则与原数据对象的 shape 相同。

In [20]:
arr1=np.array([1,2,3,4,5])  
arr2=np.array(arr1)  
print(arr2)

[1 2 3 4 5]


#### asarray 方法
方法：numpy.asarray(object，dtype)

- object 为要转化为 Numpy 数组的数据对象，可以为列表、元组或者数组；
- dtype 为转化后数组的数据类型，若不设置则与原数据对象的数据类型保持一致。

In [21]:
arr1=np.array([1,2,3,4,5])  
arr3=np.asarray(arr1)  
print(arr3)

[1 2 3 4 5]


#### copy 方法
方法：numpy.copy(object)

- object 为要创建副本的数据对象，可以为列表、元组或者数组。



In [22]:
arr1=np.array([1,2,3,4,5])  
arr4=np.copy(arr1)  
print(arr4)

[1 2 3 4 5]


### 生成固定范围的数组
- 生成固定的数组即生成包含我们所需范围内的数据的数组，主要有两种方法分别为 linspace 方法和 arange 方法。

#### arange
方法：arange(start,stop,step，dtype)
- start 为数据起始点。
- stop 为数据终点。
- step 为数据之间的步长，默认为 1。
- dtype 用于指定数组的数据类型，默认为浮点型。

In [11]:
[i for i in range(0, 20, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [12]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
[i for i in range(0, 1, 0.2)]

TypeError: 'float' object cannot be interpreted as an integer

In [23]:
np.arange(0, 1, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [24]:
[i for i in range(0, 10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [25]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### linspace

方法：linspace(start,stop,num)

- start 为数据的起始点。
- stop 为数据的结束点。
- num 为等步长生成的数据量。

In [28]:
np.linspace(0, 20, 10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [29]:
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

左闭右闭

In [31]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### 生成随机数组

##### rand

rand 用于生成 0-1 区间内指定数量的均匀分布的随机数组。

In [43]:
arr=np.random.rand(15)  
arr


array([0.77827088, 0.49180678, 0.68302993, 0.08597428, 0.81129336,
       0.64797842, 0.25339335, 0.975402  , 0.70053456, 0.68315067,
       0.40630825, 0.51551094, 0.02961524, 0.16194986, 0.68858315])

##### randint

In [34]:
np.random.randint(0, 10)    # [0, 10)之间的随机数

9

In [35]:
np.random.randint(0, 10, 10)

array([9, 1, 9, 5, 2, 6, 0, 0, 7, 0])

In [38]:
np.random.randint(0, 1, 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [39]:
np.random.randint(0, 10, size=10)

array([0, 1, 2, 5, 6, 0, 7, 5, 9, 7])

In [40]:
np.random.randint(0, 10, size=(3,5))

array([[8, 1, 6, 0, 9],
       [4, 4, 2, 3, 2],
       [7, 5, 3, 2, 4]])

In [41]:
np.random.randint(10, size=(3,5))

array([[6, 3, 4, 2, 5],
       [7, 1, 5, 6, 8],
       [1, 8, 5, 8, 5]])

##### seed

In [44]:
np.random.seed(666)

In [45]:
np.random.randint(0, 10, size=(3, 5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

In [46]:
np.random.seed(666)
np.random.randint(0, 10, size=(3,5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

##### random

In [47]:
np.random.random()

0.7315955468480113

In [48]:
np.random.random((3,5))

array([[0.8578588 , 0.76741234, 0.95323137, 0.29097383, 0.84778197],
       [0.3497619 , 0.92389692, 0.29489453, 0.52438061, 0.94253896],
       [0.07473949, 0.27646251, 0.4675855 , 0.31581532, 0.39016259]])

##### normal


方法：normal(loc,scale,size)。

- loc 为正态分布数组的均值，
- scale 为数组的方差，
- 通过 size 属性我们能够设置数组的形状或者数据量。


In [49]:
np.random.normal()

0.9047266176428719

In [52]:
np.random.normal(10, 100)

177.8190210883876

In [51]:
np.random.normal(0, 1, (3, 5))

array([[ 0.82101369,  0.36712592,  1.65399586,  0.13946473, -1.21715355],
       [-0.99494737, -1.56448586, -1.62879004,  1.23174866, -0.91360034],
       [-0.27084407,  1.42024914, -0.98226439,  0.80976498,  1.85205227]])

`np.random.<TAB>` 查看random中的更多方法

In [ ]:
np.random?

In [ ]:
np.random.normal?

In [14]:
help(np.random.normal)

Help on method normal in module numpy.random.mtrand:

normal(loc=0.0, scale=1.0, size=None) method of numpy.random.mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    .. note::
        New code should use the `~numpy.random.Generator.normal`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
