##  ``Numpy`` 中的比较和Fancy Indexing

### Fancy Indexing

神奇索引

In [1]:
import numpy as np

x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [2]:
x[3]

np.int64(3)

In [3]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [4]:
x[3:9:2]

array([3, 5, 7])

In [5]:
[x[3], x[5], x[7]]

[np.int64(3), np.int64(5), np.int64(7)]

In [6]:
ind = [3, 5, 7]
x[ind]

array([3, 5, 7])

第一行数据取[0,2] 第０列和第二列,  第二行数据取[1,3] ，第一列和第三列

In [7]:
ind = np.array([[0, 2], [1, 3]])
x[ind]

array([[0, 2],
       [1, 3]])

#### Fancy Indexing 应用在二维数组

In [8]:
print(x)
X = x.reshape(4, -1)
X

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
row = np.array([0, 1, 2])
col = np.array([1, 2, 3])
X[row, col]

array([ 1,  6, 11])

In [12]:
X[0, col]

array([1, 2, 3])

In [13]:
X[:2, col]

array([[1, 2, 3],
       [5, 6, 7]])

In [15]:
col = [True, False, True, True]

In [16]:
X[0, col]

array([0, 2, 3])

### ``numpy.array`` 的比较

In [17]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [18]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [19]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [20]:
x <= 3

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [ ]:
x >= 3

In [ ]:
x == 3

In [ ]:
x != 3

In [21]:
2 * x == 24 - 4 * x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [22]:
X < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

### 使用 ``numpy.array`` 的比较结果 

In [27]:
np.count_nonzero( x <= 3)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [28]:
np.sum(x <= 3)
# 4个数量

np.int64(4)

In [29]:
np.sum(X % 2 == 0, axis=0)

array([4, 0, 4, 0])

In [30]:
np.sum(X % 2 == 0, axis=1)

array([2, 2, 2, 2])

In [31]:
np.any(x == 0)

np.True_

In [32]:
np.any(x < 0)

np.False_

In [33]:
np.all(x > 0)

np.False_

In [34]:
np.all(x >= 0)

np.True_

In [35]:
np.all(X > 0, axis=1)

array([False,  True,  True,  True])

In [36]:
np.sum((x > 3) & (x < 10))

np.int64(6)

In [37]:
np.sum((x > 3) && (x < 10))

SyntaxError: invalid syntax (1322174247.py, line 1)

In [38]:
np.sum((x % 2 == 0) | (x > 10))

np.int64(11)

In [39]:
np.sum(~(x == 0))

np.int64(15)

### 比较结果和Fancy Indexing

In [40]:
x < 5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [41]:
x[x < 5]

array([0, 1, 2, 3, 4])

In [42]:
x[x % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [43]:
X[X[:,3] % 3 == 0, :]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])