##  scikit-learn 中的 kNN 

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
raw_data_X = [[3.393533211, 2.331273381],
              [3.110073483, 1.781539638],
              [1.343808831, 3.368360954],
              [3.582294042, 4.679179110],
              [2.280362439, 2.866990263],
              [7.423436942, 4.696522875],
              [5.745051997, 3.533989803],
              [9.172168622, 2.511101045],
              [7.792783481, 3.424088941],
              [7.939820817, 0.791637231]
             ]
raw_data_y = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]

X_train = np.array(raw_data_X)
y_train = np.array(raw_data_y)

x = np.array([8.093607318, 3.365731514])

运行命令行，加载python函数

In [3]:
%run kNN_function/kNN.py

In [6]:
# 和01实现的一样，这里用函数封装了一遍
predict_y = kNN_classify(6, X_train, y_train, x)

In [7]:
predict_y

np.int64(1)

### 使用scikit-learn中的kNN

In [8]:
from sklearn.neighbors import KNeighborsClassifier

In [9]:
kNN_classifier = KNeighborsClassifier(n_neighbors=6)

In [10]:
kNN_classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=6)

In [11]:
# kNN_classifier.predict(x)

ValueError: Expected 2D array, got 1D array instead:
array=[8.09360732 3.36573151].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [12]:
X_predict = x.reshape(1, -1)
# 变成一个 矩阵

In [13]:
X_predict 

array([[8.09360732, 3.36573151]])

In [14]:
kNN_classifier.predict(X_predict)

array([1])

In [15]:
y_predict = kNN_classifier.predict(X_predict)

In [16]:
y_predict[0]

np.int64(1)

In [17]:
y_predict

array([1])

### 重新整理我们的kNN的代码

代码参见 [这里](kNN/KNN.py)

In [18]:
%run kNN/kNN.py

In [19]:
knn_clf = KNNClassifier(3)

In [20]:
knn_clf.fit(X_train, y_train)

KNN(k=3)

In [21]:
y_predict = knn_clf.predict(X_predict)

In [22]:
y_predict

array([1])

In [23]:
y_predict[0]

np.int64(1)