## 精准度和召回率的平衡

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn import datasets

digits = datasets.load_digits()
X = digits.data
y = digits.target.copy()

y[digits.target==9] = 1
y[digits.target!=9] = 0

In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=666)

In [4]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)
y_predict = log_reg.predict(X_test)

/opt/anaconda3/envs/myenv3.10/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [5]:
from sklearn.metrics import f1_score

f1_score(y_test, y_predict)

np.float64(0.8674698795180723)

In [6]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_predict)

array([[403,   2],
       [  9,  36]])

In [7]:
from sklearn.metrics import precision_score

precision_score(y_test, y_predict)

np.float64(0.9473684210526315)

In [8]:
from sklearn.metrics import recall_score

recall_score(y_test, y_predict)

np.float64(0.8)

In [9]:
log_reg.decision_function(X_test)[:10]

array([-21.39632803, -32.89836755, -16.42503064, -79.82740073,
       -48.03006253, -24.18016394, -44.61773888, -24.2382381 ,
        -1.1442306 , -19.00687291])

In [10]:
log_reg.predict(X_test)[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
decision_scores = log_reg.decision_function(X_test)
print(decision_scores) # 每个样本的 score 值 

[-21.39632803 -32.89836755 -16.42503064 -79.82740073 -48.03006253
 -24.18016394 -44.61773888 -24.2382381   -1.1442306  -19.00687291
 -65.82579222 -50.97384945 -30.91383804 -45.95001961 -37.36079287
 -29.52191392 -36.92525489 -82.81936974 -37.64655242  -9.87455985
  -9.27181223 -85.26072092 -16.75200555 -45.34187288  -5.02565958
 -48.30720246 -11.65686706 -37.35115796 -25.08294084 -13.59519777
 -16.59094522 -28.7868136  -34.37187546 -28.52250796  -8.12118919
  -4.61236199 -21.9213878  -21.88101143 -31.15032516 -23.37622916
 -26.90704067 -62.23845924 -37.68292314 -66.36540349 -20.10762829
 -16.67567208 -18.17120489 -21.54706516 -28.96499959 -19.61221275
   2.42106669   7.72579943 -34.86440796 -42.71126562 -25.63790717
 -34.75654341  -7.59704356 -49.51935699 -51.52679169  19.66635111
 -10.10862009 -32.01145468 -11.49933661  -1.44233748 -48.69944223
 -43.86134828 -24.84126264 -19.60577522 -36.64996545  -3.52583948
  -4.45221101 -19.2151373  -20.35656157 -40.89711366 -11.85824617
 -32.75336

In [12]:
np.min(decision_scores)

np.float64(-85.73589062374965)

In [13]:
np.max(decision_scores)

np.float64(19.908950489969612)

In [14]:
# 使用新的预测值， 默认这个decision_scores =0 ，>=5分类为1，<5分类为0 
y_predict_2 = np.array(decision_scores >= 5, dtype='int')

In [15]:
confusion_matrix(y_test, y_predict_2)

array([[404,   1],
       [ 21,  24]])

In [16]:
precision_score(y_test, y_predict_2)

np.float64(0.96)

In [17]:
recall_score(y_test, y_predict_2)

np.float64(0.5333333333333333)

In [18]:
# >=-5分类为1  小于-5 分类为0
y_predict_3 = np.array(decision_scores >= -5, dtype='int')

In [19]:
confusion_matrix(y_test, y_predict_3)

array([[390,  15],
       [  5,  40]])

In [20]:
precision_score(y_test, y_predict_3)

np.float64(0.7272727272727273)

In [21]:
recall_score(y_test, y_predict_3)

np.float64(0.8888888888888888)