##  ``numpy.array`` 中的运算

给定一个数组，让数组中每一个数乘以2

In [1]:
n = 10
L = [i for i in range(n)]

In [2]:
2 * L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
A = []
for e in L:
    A.append(2*e)

In [4]:
n = 1000000
L = [i for i in range(n)]

In [5]:
%%time
A = []
for e in L:
    A.append(2*e)

CPU times: user 76.3 ms, sys: 11.6 ms, total: 87.9 ms
Wall time: 87.7 ms


In [6]:
%%time
A = [2*e for e in L]

CPU times: user 41.1 ms, sys: 12.7 ms, total: 53.8 ms
Wall time: 53 ms


In [7]:
import numpy as np
L = np.arange(n)

In [8]:
%%time
A = np.array(2*e for e in L)

CPU times: user 7.14 ms, sys: 1.53 ms, total: 8.67 ms
Wall time: 8.69 ms


In [9]:
%%time
A = 2 * L

CPU times: user 1.49 ms, sys: 1.82 ms, total: 3.31 ms
Wall time: 2.32 ms


In [10]:
n = 10
L = np.arange(n)
2 * L

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### NumPy’s UFuncs (Universal Functions)

In [11]:
X = np.arange(1, 16).reshape((3, 5))
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [12]:
X + 1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [13]:
X - 1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
X * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [15]:
X / 2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [16]:
X // 2

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]])

In [17]:
X ** 2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]])

In [18]:
X % 2

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]])

In [19]:
1 / X

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [20]:
np.abs(X)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [21]:
np.sin(X)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [22]:
np.cos(X)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153],
       [ 0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791]])

In [23]:
np.tan(X)

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00, -3.38051501e+00],
       [-2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
        -4.52315659e-01,  6.48360827e-01],
       [-2.25950846e+02, -6.35859929e-01,  4.63021133e-01,
         7.24460662e+00, -8.55993401e-01]])

In [24]:
np.arctan(X)

array([[0.78539816, 1.10714872, 1.24904577, 1.32581766, 1.37340077],
       [1.40564765, 1.42889927, 1.44644133, 1.46013911, 1.47112767],
       [1.48013644, 1.48765509, 1.49402444, 1.49948886, 1.50422816]])

In [25]:
np.exp(X)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [26]:
np.exp2(X)

array([[2.0000e+00, 4.0000e+00, 8.0000e+00, 1.6000e+01, 3.2000e+01],
       [6.4000e+01, 1.2800e+02, 2.5600e+02, 5.1200e+02, 1.0240e+03],
       [2.0480e+03, 4.0960e+03, 8.1920e+03, 1.6384e+04, 3.2768e+04]])

In [27]:
np.power(3, X)

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]])

In [28]:
np.log(X)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [29]:
np.log2(X)

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809],
       [3.45943162, 3.5849625 , 3.70043972, 3.80735492, 3.9068906 ]])

In [30]:
np.log10(X)

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ],
       [1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126]])

### 矩阵运算

In [31]:
A = np.arange(4).reshape(2, 2)
A

array([[0, 1],
       [2, 3]])

In [32]:
B = np.full((2, 2), 10)
B

array([[10, 10],
       [10, 10]])

In [33]:
A + B

array([[10, 11],
       [12, 13]])

In [34]:
A - B

array([[-10,  -9],
       [ -8,  -7]])

In [35]:
A * B

array([[ 0, 10],
       [20, 30]])

In [36]:
A.dot(B)

array([[10, 10],
       [50, 50]])

矩阵的转置

In [37]:
A.T

array([[0, 2],
       [1, 3]])

In [38]:
C = np.full((3, 3), 666)

In [55]:
A + C 

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

#### 向量和矩阵的运算

#### 加法

In [39]:
v = np.array([1, 2])

In [40]:
v + A

array([[1, 3],
       [3, 5]])

``v + A`` 是可以的，``numpy.array``的broadcast

vstack 堆叠

In [41]:
np.vstack([v] * A.shape[0])

array([[1, 2],
       [1, 2]])

In [42]:
np.vstack([v] * A.shape[0]) + A

array([[1, 3],
       [3, 5]])

#### tile 方法： 
copy形, (2,1) 就是 copy ２行， 列不copy

In [43]:
np.tile(v, (2, 1))

array([[1, 2],
       [1, 2]])

In [44]:
np.tile(v, (2, 1)) + A

array([[1, 3],
       [3, 5]])

In [45]:
np.tile(v, (2, 2))

array([[1, 2, 1, 2],
       [1, 2, 1, 2]])

#### 乘法

In [46]:
v * A

array([[0, 2],
       [2, 6]])

In [47]:
v.dot(A)

array([4, 7])

In [48]:
A.dot(v)

array([2, 8])

### 矩阵的逆

矩阵与矩阵相乘 = 单位阵

- 方阵才有逆矩阵
- 非放阵我们可以求违逆矩阵， 非１无限接近０的

In [49]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [50]:
invA = np.linalg.inv(A)

In [51]:
A.dot(invA)

array([[1., 0.],
       [0., 1.]])

In [52]:
invA.dot(A)

array([[1., 0.],
       [0., 1.]])

In [53]:
X = np.arange(16).reshape((2, 8))

In [54]:
invX = np.linalg.inv(X)

LinAlgError: Last 2 dimensions of the array must be square

#### 矩阵的伪逆

In [56]:
pinvX = np.linalg.pinv(X)
pinvX

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -1.73472348e-18],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])

In [57]:
X.dot(pinvX)

array([[ 1.00000000e+00, -1.38777878e-16],
       [ 4.44089210e-16,  1.00000000e+00]])

矩阵的伪逆又被称为“广义逆矩阵”。中文wiki链接: [https://zh.wikipedia.org/wiki/%E5%B9%BF%E4%B9%89%E9%80%86%E9%98%B5](https://zh.wikipedia.org/wiki/%E5%B9%BF%E4%B9%89%E9%80%86%E9%98%B5)

### 矩阵的转置。

矩阵的转置是一种基本的线性代数操作，通过将原矩阵的行转换为列，列转换为行来创建一个新的矩阵。 对于向量，转置实际上不会改变向量的形状，因为向量本身只有一行或一列。因此，向量的转置结果与原向量相同。 例如，向量A[1, 2, 3]的转置表示为A^T = [[1], [2], [3]]。 对于2维矩阵B = [[1, 2, 3], [4, 5, 6]]，这是一个2x3的矩阵。它的转置操作将其变为一个3x2的矩阵，即B^T = [[1, 4], [2, 5], [3, 6]]。

mat 方法用于将二维结构的数值型数据对象转化为 Numpy 的矩阵类型。

- 方法：numpy.mat(data, dtype=None)，其中 data 要求为一个数值型的二维数组或者列表或者元组，dtype 为矩阵的数据类型。

In [3]:
import numpy as np 
arr=np.array([[98,89],[64,90],[60,56],[92,78],[32,45],[48,30]])  
print(type(arr))  
matrixarr=np.asmatrix(arr)  
print(type(matrixarr))

<class 'numpy.ndarray'>
<class 'numpy.matrix'>


In [4]:
fruit_price=np.array([[5,4,3]])  
fudu=np.array([1.5,0.75,3])  
print('水果价格浮动后价格为:\n',fruit_price*fudu)

水果价格浮动后价格为:
 [[7.5 3.  9. ]]


### 矩阵与矩阵的乘法

运算符号：@或*。当我们使用 ndarray 存储矩阵时，需要使用 @ 实现矩阵的乘法以区别于二维数组的数乘。当我们使用 matrix 存储矩阵时，我们可以直接用*完成矩阵的乘法。

- 矩阵乘法公式： 设矩阵 A 是一个 m×n 的矩阵，矩阵 B 是一个 n×p 的矩阵，那么它们的乘积 C 是一个 m×p 的矩阵
- 运算规则：需要注意进行矩阵乘法的两个矩阵要求前一个矩阵的列要和后一个矩阵的行的轴长相同，只有保证这个条件才能够进行矩阵乘法。也就是说前面的矩阵的列数和后面矩阵的行数一致两个矩阵才能点乘。 同时矩阵乘法是满足结合律并不满足交换律的，即 ABC 等于 A(BC)，不等于 ACB。
- 我们的数据的维度往往是不符合要求的，这是就需要进行升维。升维主要有两个方法，分别为 reshape 方法和 newaxis 方法，下面我们就来看看如何使用这两种方法对数组进行升维吧！

#### reshape 方法
- 方法：numpy.reshape(arr, newshape)，其中 arr 为待处理数组，newshape 新数组的形状。


我们利用 reshape 函数成功将一个大小为 6 的一维数组，升维成了一个二行三列的二维数组，这样便可以实现矩阵乘法。

In [5]:
arr = np.array([1,2,3,4,5,6])  
arr2=np.reshape(arr,(2,3))  
print(arr2)

[[1 2 3]
 [4 5 6]]


#### Newaxis 方法
- np.newaxis() 是 NumPy 中的一个函数，用于创建一个新的轴，用于多维数组的扩展。它返回一个表示新轴的整数索引。




In [6]:
arr = np.array([1,2,3,4,5,6])  
arr2=arr[np.newaxis,:]  
print('升维后的数组为{}，形状为{}'.format(arr2,arr2.shape))

升维后的数组为[[1 2 3 4 5 6]]，形状为(1, 6)


In [7]:
arr = np.array([1,2,3,4,5,6])  
arr2=arr[:,np.newaxis]  
print('升维后的数组为{}，形状为{}'.format(arr2,arr2.shape))

升维后的数组为[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]，形状为(6, 1)


### dot 方法
dot 方法有两个功能分别为向量点积和矩阵乘法。当两个数组为二维数组（矩阵）且满足矩阵乘法的要求时，利用 dot 方法便能够实现矩阵乘法；当输入的两个数组的形状相同时，利用 dot 方法就能求得这两个数组的点积（所谓矩阵的点积即两个数组对应位置的元素相乘，最后将所有位置的乘法结果相加便得到两个数组的点积）。

- 方法：np.dot(A,B)，其中 A 和 B 为进行运算的数组。



In [2]:
import numpy as np 
fruit_price=np.array([[5,4,3]])  
jinshu=np.array([[2],[3],[1]])  
print('水果的总价格为:\n',fruit_price@jinshu)  
print('水果的总价格为:\n',np.dot(fruit_price,jinshu))
print(np.sum(np.dot(fruit_price,jinshu)))
#  numpy 数组提供的矩阵乘法符号 @ 或者 dot 方法实现矩阵乘法，便可以非常方便地获取总价格


水果的总价格为:
 [[25]]
水果的总价格为:
 [[25]]
25


### matmul 方法

matmul 方法用于实现矩阵乘法，如果两个输入的数组其中一个为一维，另外一个数组为二维，该函数会自动对一维数组进行升维然后实现矩阵乘法。

- 方法：matmul(A,B)。


下面同样我们就以顾客购买水果为例，为大家展示矩阵乘法。例如：张三想要买两斤苹果、三斤李子、一斤桃子，那么如何通过 matmul 方法求得水果的总价呢？

In [15]:
fruit_price=np.asmatrix([[5,4,3]])
jinshu=np.array([2,3,1])
print('np.matmul，水果的总价格为:\n',np.matmul(fruit_price,jinshu))

# print('fruit_price*jinshu，水果的总价格为:\n',fruit_price*jinshu)  报错


np.matmul，水果的总价格为:
 [[25]]
