##  ``Numpy`` 中的聚合操作

### numpy计算函数

方法：add() 加法函数，subtract() 减法函数，multiply() 乘法函数，divide() 除法函数，mod() 取余函数。

### 统计函数
- Mean	求平均值
- median 求中位数
- Sum	求和
- Max/min	求最大值最小值
- Std/var	标准差/方差
- Argmax/argmin	求最大值最小值下标
- prod 所有元素相乘



In [1]:
import numpy as np
Score=np.array([[69 ,70] ,[80 ,92], [90, 63],[40, 20],[60, 50],[20, 96],[90, 33],[94 ,44],[90, 55],[99 ,30]])#学生前后两次的成绩表
Score_F=np.array([69,80,90,40,60,20,90,94,90,99])#第一次成绩
Score_S=np.array([70,92,63,20,50,96,33,44,55,30])#第二次成绩
Score_chaju=np.subtract(Score_F,Score_S)
print('查看两次成绩的差距',Score_chaju)
print('查看两次成绩的差距，差距以正数显示',np.abs(Score_chaju))
print('求两次成绩的和',np.add(Score_F,Score_S))
# 用第一次成绩的 0.6 倍加第二次成绩的 0.4 倍作为最终成绩，混合使用加法、乘法函数。示例如下：
print('第一次成绩的0.6加第二次成绩的0.4',np.add(np.multiply(Score_F,0.6),np.multiply(Score_S,0.4)))

print('百分制转换成十分制',np.divide(Score,10))


print('对浮动的数值进行开方，放缩：',np.sqrt(np.abs(Score_chaju)))

print('对浮动值进行平方，放大',np.square(np.abs(Score_chaju)))  
print('求浮动值的4次幂',np.power(np.abs(Score_chaju),4))


查看两次成绩的差距 [ -1 -12  27  20  10 -76  57  50  35  69]
查看两次成绩的差距，差距以正数显示 [ 1 12 27 20 10 76 57 50 35 69]
求两次成绩的和 [139 172 153  60 110 116 123 138 145 129]
第一次成绩的0.6加第二次成绩的0.4 [69.4 84.8 79.2 32.  56.  50.4 67.2 74.  76.  71.4]
百分制转换成十分制 [[6.9 7. ]
 [8.  9.2]
 [9.  6.3]
 [4.  2. ]
 [6.  5. ]
 [2.  9.6]
 [9.  3.3]
 [9.4 4.4]
 [9.  5.5]
 [9.9 3. ]]
对浮动的数值进行开方，放缩： [1.         3.46410162 5.19615242 4.47213595 3.16227766 8.71779789
 7.54983444 7.07106781 5.91607978 8.30662386]
对浮动值进行平方，放大 [   1  144  729  400  100 5776 3249 2500 1225 4761]
求浮动值的4次幂 [       1    20736   531441   160000    10000 33362176 10556001  6250000
  1500625 22667121]


In [2]:
L = np.random.random(100)
sum(L)

np.float64(49.853623071844495)

In [3]:
np.sum(L)

np.float64(49.85362307184448)

In [4]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

81.9 ms ± 769 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)
200 μs ± 1.36 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


### min, max

In [5]:
np.min(big_array)

np.float64(4.476459718461001e-07)

In [6]:
np.max(big_array)

np.float64(0.9999960011127178)

In [7]:
big_array.min()

np.float64(4.476459718461001e-07)

In [8]:
big_array.max()

np.float64(0.9999960011127178)

In [9]:
big_array.sum()

np.float64(500137.927918418)

### 多维度聚合

In [10]:
X = np.arange(16).reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
np.sum(X)

np.int64(120)

In [12]:
np.sum(X, axis=0)

array([24, 28, 32, 36])

In [13]:
np.sum(X, axis=1)

array([ 6, 22, 38, 54])

注意：axis描述的是将要被压缩的维度。

### 其他聚合操作

prod所有元素相乘

In [14]:
np.prod(X)

np.int64(0)

In [15]:
np.prod(X + 1)

np.int64(20922789888000)

In [16]:
np.mean(X)

np.float64(7.5)

median中位数， 如果是偶数个数则返回平均数

In [17]:
np.median(X)

np.float64(7.5)

In [18]:
v = np.array([1, 1, 2, 2, 10])
np.mean(v)

np.float64(3.2)

In [19]:
np.median(v)

np.float64(2.0)

percentile ,百分位数

np.percentile(a,q,axis)

In [20]:
np.percentile(big_array, q=50)

np.float64(0.5002359216542247)

In [21]:
np.median(big_array)

np.float64(0.5002359216542247)

In [22]:
np.percentile(big_array, q=100)

np.float64(0.9999960011127178)

In [23]:
np.max(big_array)

np.float64(0.9999960011127178)

In [24]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q=percent))

4.476459718461001e-07
0.2498524833073445
0.5002359216542247
0.7504363996854757
0.9999960011127178


In [25]:
np.var(big_array)

np.float64(0.08343264706522127)

In [26]:
np.std(big_array)

np.float64(0.2888470998040681)

In [27]:
x = np.random.normal(0, 1, 1000000)

In [28]:
np.mean(x)

np.float64(-0.0005579253820011571)

In [29]:
np.std(x)

np.float64(1.0010114502850682)