## 03 训练数据集和测试数据集拆分

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets 

In [2]:
# 加载 莺尾花数据
iris = datasets.load_iris()
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [3]:
X = iris.data

In [4]:
y = iris.target

In [5]:
X.shape
# 花有４个特征，１５０个样本

(150, 4)

In [6]:
y.shape

(150,)

### train_test_split

分离出一部分数据做训练，另外一部分数据做测试。

In [7]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
shuffled_indexes = np.random.permutation(len(X))
shuffled_indexes

array([ 50,  40,  85,  99, 136, 110,  43,  31,  57,  75, 143, 111,  72,
        21,  19,  84,  51,   9,   3,  16, 114,  96,  22, 149,  37,  44,
       130, 100,  98, 104, 141, 132, 103,  52, 135,  91,  80, 108,  30,
       107,  18, 127, 121,  77,  68,  58, 122,  41,  56,  95,  17,  89,
        53, 117, 145,  65,  82,  11,  24,  94, 125,  10,  67,  23,  38,
       146,  63,  81,  26,   8,  15, 113,  88,  29, 116,  73,  48, 119,
        87,  33, 106,  86,  97, 144,  42, 128, 102,  55, 142,  78,   4,
        92,  49,  12, 140,  70,  27,  13,  62, 147,  47,  60, 120, 139,
        93,  76,   6,  64, 138, 105,  35, 131,  69, 134,  28, 124,  46,
         1, 126, 101,  14, 133,  74, 148,  54, 123, 129,  32,  61,   0,
        71,  36,  83,   7,  45, 115,   2, 112, 137,  59,  25,  39,  34,
        66,   5,  20,  90, 118,  79, 109])

In [9]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [10]:
test_indexes = shuffled_indexes[:test_size]
train_indexes = shuffled_indexes[test_size:]

In [11]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [12]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [13]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


#### 封装

In [14]:
from playML.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

In [15]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [16]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


#### 测试我们的算法

In [23]:
from playML import kNN
my_knn_clf = kNN.KNNClassifier(k=3)
my_knn_clf.fit(X_train, y_train)
y_predict = my_knn_clf.predict(X_test)

In [19]:
y_predict

array([1, 2, 2, 0, 0, 2, 2, 1, 2, 0, 2, 2, 2, 1, 1, 1, 0, 0, 1, 2, 2, 2,
       2, 2, 2, 0, 2, 0, 2, 1])

In [20]:
y_test

array([1, 2, 2, 0, 0, 2, 2, 1, 1, 0, 2, 2, 2, 2, 1, 1, 0, 0, 1, 2, 2, 2,
       2, 2, 2, 0, 2, 0, 2, 1])

In [21]:
sum(y_predict == y_test)

np.int64(28)

In [22]:
sum(y_predict == y_test) / len(y_test)

np.float64(0.9333333333333333)

#### sklearn中的train_test_split

In [24]:
from sklearn.model_selection import train_test_split

train_test_split

<function sklearn.model_selection._split.train_test_split(*arrays, test_size=None, train_size=None, random_state=None, shuffle=True, stratify=None)>

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [26]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [27]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)
