## ``numpy.array`` 合并和分割


### concatenate 方法
- concatenate 方法较为灵活，它既能够实现数组的水平合并，也能够实现数组的垂直合并，主要通过设置参数 axis 合并轴向来完成。

- 方法：concatenate(arrays,axis,dtype)。
- 其中，arrays 为待合并的数组序列；
- axis 为合并轴向，设置为 0 时为垂直合并，设置为 1 时为水平合并，默认设置为 0；
- dtype 为合并后数组的数据类型。


### hstack 方法
- hstack 方法能够对数组进行水平合并。
- 方法：numpy.hstack(arrays)，其中 arrays 为要合并的数组序列。

### column_stack 方法
方法：column_stack(tup)，其中 tup 为要合并的数组序列。

感觉效果和hstack一致


### vstack 方法
- 能够对数组进行垂直合并，观察该方法我们发现其与 hstack 只有一个字符的差别，hstack 的 h 代表水平，vstack 中的 v 代表垂直，所以 vstack 用于实现数组的垂直合并。
- 方法：numpy.vstack(arrays)，其中 arrays 为要合并的数组序列。


### row_stack 方法
- row_stack 与 column_stack 是对应的，row 是行的意思，column 是列的意思，所以 row_stack 是按行合并，column_stack 是行列合并。
- 方法：row_stack(tup)，其中 tup 用于指出待垂直合并的数组序列。

In [1]:
import numpy as np

### ``numpy.array`` 的合并

In [2]:
Stock1=np.array([[14.322,14.552],[14.472,14.532],[14.592,15.022],[14.852,14.802]])  
Stock2=np.array([[14.652,14.192],[14.832,14.422],[15.022,14.592],[15.152,14.722]])  
# axis=1 水平合并
Stock=np.concatenate((Stock1,Stock2),axis=1)  
print(Stock)

[[14.322 14.552 14.652 14.192]
 [14.472 14.532 14.832 14.422]
 [14.592 15.022 15.022 14.592]
 [14.852 14.802 15.152 14.722]]


In [3]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [4]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [5]:
z = np.array([666, 666, 666])
np.concatenate([x, y, z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [6]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
np.concatenate([A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [7]:
np.concatenate([A, A], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [8]:
np.concatenate([A, z])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [9]:
np.concatenate([A, z.reshape(1, -1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

vstack 方法能够对数组进行垂直合并，观察该方法我们发现其与 hstack 只有一个字符的差别，hstack 的 h 代表水平，vstack 中的 v 代表垂直，所以 vstack 用于实现数组的垂直合并。

方法：numpy.vstack(arrays)，其中 arrays 为要合并的数组序列。

In [10]:
np.vstack([A, z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [11]:
B = np.full((2,2), 100)

In [12]:
np.hstack([A, B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

In [13]:
np.hstack([A, z])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

### ``numpy.array`` 的分割

#### 方法：split(array, indices_or_sections, axis)。
其中，array 为要分割的数组，indices_or_sections 可以为分割的索引值或分割数，如果是一个索引值，则将数组按照该索引值分割成两个部分；如果是一个分割数，则将数组按照等分数分割成多个部分。axis 用于指出沿着哪个轴分割数组。axis=0，按行分割。axis=1，按列分割。

In [31]:
x = np.arange(10)
x    

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
x1, x2, x3 = np.split(x, [3, 7])

In [33]:
x1

array([0, 1, 2])

In [34]:
x2

array([3, 4, 5, 6])

In [35]:
x3

array([7, 8, 9])

In [36]:
x1, x2 = np.split(x, [5])

In [37]:
x1

array([0, 1, 2, 3, 4])

In [38]:
x2

array([5, 6, 7, 8, 9])

In [39]:
A = np.arange(16).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [40]:
A1, A2 = np.split(A, [2])

In [41]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [42]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [43]:
A1, A2 = np.split(A, [2], axis=1)

In [44]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [45]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [46]:
upper, lower = np.vsplit(A, [2])

In [47]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [48]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
left, right = np.hsplit(A, [2])

In [50]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [51]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [52]:
data = np.arange(16).reshape((4, 4))
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [53]:
X, y = np.hsplit(data, [-1])

In [54]:
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [55]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [56]:
y[:, 0]

array([ 3,  7, 11, 15])