## 01 ``numpy.array`` 基础,shape,dim,size,dtype

In [2]:
import numpy

In [3]:
numpy.__version__

'2.0.0'

In [4]:
import numpy as np

In [5]:
np.__version__

'2.0.0'

### Python List的特点

In [6]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
L[5]

5

In [7]:
L[5] = 100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [8]:
L[5] = "Machine Learning"
L

[0, 1, 2, 3, 4, 'Machine Learning', 6, 7, 8, 9]

Python的List不要求存储同样的类型，带来效率问题。

In [10]:
import array
arr = array.array('i', [i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr[5]

5

In [12]:
arr[5] = 100
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

In [14]:
arr[5] = "Machine Learning"

TypeError: an integer is required (got type str)

In [15]:
arr[5] = 5.0

TypeError: integer argument expected, got float

``array``的缺点是没有将数据当做向量或者矩阵，不支持基本运算。

### ``numpy.array``

In [9]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
nparr[5] = 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [11]:
nparr[5] = "Machine Learning"

ValueError: invalid literal for int() with base 10: 'Machine Learning'

dtype 是 ndarray 的数据类型

In [12]:
nparr.dtype

dtype('int64')

#####  自动强转

In [26]:
nparr[5] = 3.14
nparr

array([0, 1, 2, 3, 4, 3, 6, 7, 8, 9])

In [27]:
nparr2 = np.array([1, 2, 3.0])
nparr2.dtype

dtype('float64')

## shape 

In [14]:
nparr3 = np.array([[1, 2, 3], [4, 5, 6]])
nparr3.shape

(2, 3)

In [15]:
nparr3.dtype


dtype('int64')

In [16]:
nparr3.ndim

2

In [17]:
nparr3.size

6